group = 'by.mrflaxe'
version = '0.1.0-SNAPSHOT'

subprojects {
    apply plugin: 'java-library'

    dependencies {
        compileOnly("org.projectlombok:lombok:1.18.42")
        annotationProcessor("org.projectlombok:lombok:1.18.42")

        compileOnly 'org.jetbrains:annotations:26.0.2-1'
        annotationProcessor 'org.jetbrains:annotations:26.0.2-1'

        testCompileOnly("org.projectlombok:lombok:1.18.42")
        testAnnotationProcessor("org.projectlombok:lombok:1.18.42")
    }
}