rootProject.name = 'Arbor'

include(
        ":api",
        ":core",
        ":platform",
        ":platform:bootstrap",
        ":platform:platform-bukkit"
)

dependencyResolutionManagement {
    repositories {
        mavenCentral()

        maven {
            url = 'https://libraries.minecraft.net'
        }
        maven {
            url = 'https://hub.spigotmc.org/nexus/content/groups/public/'
        }
    }
}